services:
  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    network_mode: host
    container_name: host-postgres
  keycloak:
    build:
      context: ../keycloak
      dockerfile: ../keycloak/Dockerfile
      args:
        - MAVEN_DOCKER_IMAGE=maven:3.9.2-eclipse-temurin-17
        - KEYCLOAK_DOCKER_IMAGE=quay.io/keycloak/keycloak:24.0.2
    image: keycloak-plugin:0.1.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    network_mode: host
    container_name: host-keycloak
    volumes:
      - ./extensions:/opt/keycloak/providers

volumes:
  keycloak-data:
