services:
  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    container_name: host-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    container_name: host-keycloak
    volumes:
      - ./extensions:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes   

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025" 

volumes:
  keycloak-db-data:
